### ISSUE TITLE
buster warnings

### ISSUE THREAD

**Issue by pascalandy** [StefanScherer/ghost-buster-docker#1]
Hey Stephan,

Thanks again for having put this together!

When executing `docker-compose run buster`, Im wondering if those issue are normal:
- `curl: (23) Failed writing body (0 != 16123)`
- `0Warning: Failed to create the file static/talks/index.html: No such file or
Warning: directory`
 
```
0Warning: Failed to create the file static/talks/index.html: No such file or
Warning: directory
curl: (23) Failed writing body (0 != 1791)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file static/rss/index.html: No such file or
Warning: directory
curl: (23) Failed writing body (0 != 16123)
Fixing links to https
Fixing some blog posts
Removing index.html from links
Starting ghostbuster_preview_1
```

Cheers!

**Comment by pascalandy** [comment]
Oh I get it now, `static/talks/index.html` is a page on your blog. I guess we can close this!

**Comment by StefanScherer** [comment]
Yes, that page wasn't rendered to HTML automatically. Feel free to adjust buster.sh to your needs.

**Comment by pascalandy** [comment]
Sure. Thanks again for sharing this :)
