### ISSUE TITLE
Ghost 1.0 support

### ISSUE THREAD

**Issue by julienfabre** [StefanScherer/ghost-buster-docker#3]
The Ghost team just released a 1.0 version, which incorporates some interesting features (https://dev.ghost.org/ghost-1-0-0/)

Is the support for Ghost 1.0 planned in the near future?

Their docker repository has also been updated (to Ghost 1.0.2 as i'm writing this): https://hub.docker.com/_/ghost/

Of course this is more of an enhancement than an issue.

**Comment by StefanScherer** [comment]
Thanks @julienfabre. I also waited for an updated Docker image. Seems the Docker image is some days behind official Ghost release which is 1.4.0 already :-)
I'll test the updated version an update the docker-compose.yml after that.

**Comment by julienfabre** [comment]
1.5 is live on the Docker repository, i'll run a few test myself ;)

**Comment by StefanScherer** [comment]
I tried 1.5.0 yesterday, but I need more time to look at it. It didn't find my old posts.

**Comment by StefanScherer** [comment]
See #4 for my steps.
